---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by levi.
--- DateTime: 2/19/2024 6:34 PM
---

peripheral = {
    getType = function(side)
        if side == "left" then
            return "modem"
        else
            return "unknown"
        end
    end
}

rednet = {
    CHANNEL_BROADCAST = 1,
    open = function(side)
        return true
    end,
    broadcast = function(message)
        return true
    end,
    isOpen = function(side)
        return true
    end
}

fs = {
    exists = function(path)
        return true
    end,
    makeDir = function(path)
        return true
    end,
    move = function(from, to)
        return true
    end,
    list = function(path)
        return {"log1", "log2", "log3", "log4", "log5", "log6"}
    end,
    delete = function(path)
        return true
    end,
    open = function(path, mode)
        return {
            readAll = function()
                return "log content"
            end,
            writeLine = function(line)
                return true
            end,
            close = function()
                return true
            end
        }
    end
}