---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by levi.
--- DateTime: 2/19/2024 7:28 PM
---

require('Logger')
local logger = Logger:new(Logger.levels.INFO, "MinerCore")

require('betterTurtle')
local betterTurtle = BetterTurtle:new()
require('environment')
local environment = Environment:new()
require('mutex')

function dumpWaste()
    local num_dumped = 0
    print("[dumpWaste]: Will dump the following blocks:")
    for i = 1, 14 do
        local count = betterTurtle.getItemCount( i )
        local detail = betterTurtle.getItemDetail( i )
        if detail ~= nil and has_value(waste_blocks, detail.name) then
            betterTurtle.select( i )
            betterTurtle.drop( count )
            num_dumped = num_dumped + count
            print("[dumpWaste]: - "..detail.name.." (x"..count..")")
        end
    end
    if num_dumped == 0 then
        print("[dumpWaste]: No blocks")
    end
    print("[dumpWaste]: Dumped "..num_dumped.." blocks of waste!")
    num_dumped = 0
    betterTurtle.select( 1 )
end

function dumperLoop()
    while true do
        -- lock the mutex to prevent other threads from accessing the turtle
        Mutex:lock("dumperLoop")
        dumpWaste()
        -- unlock the mutex to allow other threads to access the turtle
        Mutex:unlock("dumperLoop")
        local id = os.startTimer( 20 )
        while true do
            local _, tid = os.pullEvent( "timer" )
            if tid == id then
                break
            end
        end
    end
end