---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by levi.
--- DateTime: 2/19/2024 6:53 PM
---

require('Logger')

require('coordinate')

local logger = Logger:new(Logger.levels.DEBUG, "Environment")

require('binaryHeap')

blockType = {
    WASTE = {name = "Waste"},
    FUEL = {name = "Fuel"},
    OTHER = {name = "Other"},
    BLOCKER = {name = "Blocker"},
    AIR = {name = "Air"},
    UNKNOWN = {name = "Unkown"},
    PATH = {name = "Path"}
}

Environment = {
    checkedBlocks = {},
    wasteBlocks = {},
    blockers = {},
    fuels = {},
    fuelLocations = {},
    checkQueue = BinaryHeap:new()
}

-- ---------------------------------------------------------------------------
-- Mining patterns - pluggable strategies for choosing branch coordinates.
-- ---------------------------------------------------------------------------

Environment.patterns = {
    -- Default branch mining: every 3 blocks along x or z at y=0.
    -- Looks like:  x . . x . . x . . x
    --              .         .         .
    --              x . . x . . x . . x
    branch = function(c)
        if c.y ~= 0 then return false end
        return c.x == 0 or c.z == 0 or c.x % 3 == 0 or c.z % 3 == 0
    end,

    -- Strip mining: parallel rows along z every 4 blocks.
    strip = function(c)
        return c.y == 0 and c.z % 4 == 0
    end,

    -- Quarry: mine everything from y=0 down (and along the surface).
    quarry = function(c)
        return c.y <= 0
    end,

    -- Spiral: rings around (0,0) at y=0. Membership test (not generation).
    spiral = function(c)
        if c.y ~= 0 then return false end
        local r = math.max(math.abs(c.x), math.abs(c.z))
        return c.x == r or c.x == -r or c.z == r or c.z == -r
    end,
}
Environment.currentPattern = "branch"

-- Returns true if the given coordinate is a node on the configured mining grid.
function Environment:isMiningTarget(coordinate)
    if getmetatable(coordinate) ~= Coordinate then
        coordinate = Coordinate.parse(coordinate)
    end
    local fn = Environment.patterns[Environment.currentPattern]
    if not fn then return false end
    return fn(coordinate)
end

function Environment:getBlockAtPosition(coordinate)
    if getmetatable(coordinate) ~= Coordinate then
        coordinate = Coordinate.parse(coordinate)
    end
    if self.checkedBlocks[coordinate.y]
        and self.checkedBlocks[coordinate.y][coordinate.x]
        and self.checkedBlocks[coordinate.y][coordinate.x][coordinate.z] then
        return self.checkedBlocks[coordinate.y][coordinate.x][coordinate.z]
    elseif self:isMiningTarget(coordinate) then
        self:insertCoordToCheckedBlocks(coordinate, blockType.PATH)
        return blockType.PATH
    else
        return blockType.UNKNOWN
    end
end

function Environment:getNeighbours(coordinate)
    local neighbours = {}
    -- Use the ordered `directions.all` table for stable iteration order
    -- and to skip the `any` sentinel without a metatable check.
    for _, v in ipairs(directions.all) do
        logger:trace("Checking neighbour in direction " .. tostring(v.name))
        local neighbour = coordinate + v.vector
        logger:trace("Neighbour in direction " .. tostring(v.name) .. " is at position " .. tostring(neighbour))
        local blockType = self:getBlockAtPosition(neighbour)
        neighbours[v] = {position = neighbour, type = blockType}
    end
    return neighbours
end

-- load wasteBlocks from file
local function loadWasteBlocks()
    logger:trace("Starting to load waste blocks from file")
    local file = io.open("wasteBlocks", "r")
    local line = file:read()
    while line do
        Environment.wasteBlocks[line] = true
        line = file:read()
    end
    file:close()
    logger:trace("Finished loading waste blocks from file")
end

-- load fuels from file
local function loadFuels()
    logger:trace("Starting to load fuels from file")
    local file = io.open("fuels", "r")
    local line = file:read()
    while line do
        Environment.fuels[line] = true
        line = file:read()
    end
    file:close()
    logger:trace("Finished loading fuels from file")
end

local function loadBlockers()
    logger:debug("Starting to load blockers from file")
    local file = io.open("blockers", "r")
    local line = file:read()
    while line do
        Environment.blockers[line] = true
        line = file:read()
    end
    file:close()
    logger:debug("Finished loading blockers from file")
end

local function generateMiningMap()
    -- Mining targets are now computed lazily via Environment:isMiningTarget(c).
    -- No precomputation is needed; this function is retained as a no-op
    -- so older code paths that call it keep working.
end

loadWasteBlocks()
loadFuels()
loadBlockers()
generateMiningMap()

function Environment:new()
    local o = {}
    for k, v in pairs(Environment) do
        if type(v) == "table" then
            o[k] = {}
        end
    end
    o.wasteBlocks = Environment.wasteBlocks
    o.blockers = Environment.blockers
    o.fuels = Environment.fuels
    o.checkQueue = BinaryHeap:new()
    setmetatable(o, self)
    self.__index = self
    return o
end

function Environment:insertCoordToCheckedBlocks(coordinate, blockType)
    if getmetatable(coordinate) ~= Coordinate then
        coordinate = Coordinate.parse(coordinate)
    end
    logger:trace("Inserting coordinate " .. tostring(coordinate) .. " to checked blocks")
    self.checkedBlocks[coordinate.y] = self.checkedBlocks[coordinate.y] or {}
    self.checkedBlocks[coordinate.y][coordinate.x] = self.checkedBlocks[coordinate.y][coordinate.x] or {}
    self.checkedBlocks[coordinate.y][coordinate.x][coordinate.z] = blockType
    logger:trace("Finished inserting coordinate " .. tostring(coordinate) .. " to checked blocks")
end

Environment:insertCoordToCheckedBlocks(Coordinate:new(0, 0, 0), blockType.AIR)

function Environment:checkBlockType(block_type)
    if not block_type then
        return blockType.AIR
    end
    logger:debug("Checking block type for " .. tostring(block_type))
    if self.wasteBlocks[block_type] then
        logger:debug("Block type for " .. tostring(block_type) .. " is WASTE")
        return blockType.WASTE
    end
    if self.fuels[block_type] then
        logger:debug("Block type for " .. tostring(block_type) .. " is FUEL")
        return blockType.FUEL
    end
    if self.blockers[block_type] then
        logger:debug("Block type for " .. tostring(block_type) .. " if Blocker")
        return blockType.BLOCKER
    end
    logger:debug("Block type for " .. tostring(block_type) .. " is OTHER")
    return blockType.OTHER
end

function Environment:checkBlock(coordinate, block_type)
    logger:debug("Checking block at coordinate " .. tostring(coordinate) .. " with block type " .. tostring(block_type))
    if getmetatable(coordinate) ~= Coordinate then
        coordinate = Coordinate.parse(coordinate)
    end
    local typeInMap = self:getBlockAtPosition(coordinate)
    local _blockType = self:checkBlockType(block_type)
    if typeInMap ~= blockType.UNKNOWN then
        if _blockType == typeInMap then
            logger:debug("Block at coordinate " .. tostring(coordinate) .. " is already checked")
            return _blockType, true
        elseif _blockType ~= typeInMap then
            logger:warn("New block type for already registered block")
            logger:debug("At " .. tostring(coordinate) .. " new block type: " .. _blockType.name)
            self:insertCoordToCheckedBlocks(coordinate, _blockType)
            return _blockType, false
        end
    else
        logger:debug("New block data at " .. tostring(coordinate) .. " with type " .. _blockType.name)
        self:insertCoordToCheckedBlocks(coordinate, _blockType)
        return _blockType, false
    end

end

function Environment:storeFuelLocation(coordinate)
    logger:debug("Storing fuel location at coordinate " .. tostring(coordinate))
    if getmetatable(coordinate) ~= Coordinate then
        coordinate = Coordinate.parse(coordinate)
    end
    self.fuelLocations[coordinate.y] = self.fuelLocations[coordinate.y] or {}
    self.fuelLocations[coordinate.y][coordinate.x] = self.fuelLocations[coordinate.y][coordinate.x] or {}
    self.fuelLocations[coordinate.y][coordinate.x][coordinate.z] = blockType.FUEL
    logger:debug("Finished storing fuel location at coordinate " .. tostring(coordinate))
end

function Environment:getNearestFuelLocation(source)
    local fuelLocations = {}
    for y, v1 in pairs(self.fuelLocations) do
        for x, v2 in pairs(v1) do
            for z, _ in pairs(v2) do
                table.insert(fuelLocations, Coordinate:new(x, y, z))
            end
        end
    end
    if #fuelLocations == 0 then
        return nil, false
    end
    local path, target = self:dijkstra(source, fuelLocations)
    -- Previously this code tried to index `fuelLocations` (a flat list of
    -- Coordinates) as a [y][x][z] nested map, which silently did nothing in
    -- the best case and errored in the worst. Use the proper API instead.
    if target then
        self:removeFuelLocation(target)
    end
    return path, true
end

function Environment:removeFuelLocation(coordinate)
    if getmetatable(coordinate) ~= Coordinate then
        coordinate = Coordinate.parse(coordinate)
    end
    if self.fuelLocations[coordinate.y] and self.fuelLocations[coordinate.y][coordinate.x] then
        self.fuelLocations[coordinate.y][coordinate.x][coordinate.z] = nil
    end
end

function Environment:addPositionToCheckQueue(coordinate)
    if getmetatable(coordinate) ~= Coordinate then
        coordinate = Coordinate.parse(coordinate)
    end
    local blockType = self:getBlockAtPosition(coordinate)
    local priority = self:getCost(blockType)
    logger:debug("Adding position " .. tostring(coordinate) .. " to check queue with priority " .. tostring(priority))
    self.checkQueue:insert(coordinate, priority)
end

function Environment:getClosestMiningPositions(position)
    if getmetatable(position) ~= Coordinate then
        position = Coordinate.parse(position)
    end
    logger:debug("Getting closest mining positions to " .. tostring(position))
    local coordinates = {}
    local popped = {}
    if self.checkQueue:isEmpty() then
        -- No queued ore/lava follow-ups: pick branch-mining targets near us.
        for x = -2, 2 do
            for z = -2, 2 do
                local c = Coordinate:new(position.x + x, 0, position.z + z)
                if self:isMiningTarget(c) and not c:isEqual(position) then
                    table.insert(coordinates, c)
                end
            end
        end
    else
        -- Drain up to 5 entries from the priority queue. `pop` returns
        -- (coordinate, priority) - capture BOTH so we can re-queue the
        -- losers afterwards.
        for _ = 1, 5 do
            if self.checkQueue:isEmpty() then break end
            local coord, prio = self.checkQueue:pop()
            if not coord then break end
            table.insert(popped, {coordinate = coord, priority = prio})
            table.insert(coordinates, coord)
        end
    end
    if #coordinates == 0 then
        return {}
    end
    local path, target = self:dijkstra(position, coordinates)
    -- Re-insert the non-chosen popped candidates with a slightly better
    -- priority so they're picked sooner next time.
    for _, v in ipairs(popped) do
        if not target or not v.coordinate:isEqual(target) then
            self.checkQueue:insert(v.coordinate, (v.priority or 0) - 1)
        end
    end
    return path or {}
end

function Environment:dijkstra(source, targets)
    if getmetatable(source) ~= Coordinate then
        source = Coordinate.parse(source)
    end
    -- Normalize `targets` into a list of Coordinates.
    if getmetatable(targets) == Coordinate then
        targets = {targets}
    elseif type(targets) == "table" then
        -- Try to interpret the whole table as a single coordinate first
        -- (e.g. {1,2,3} or {x=1,y=2,z=3}). If that fails, treat it as a
        -- list of coordinates / coordinate-like tables.
        local ok, parsed = pcall(Coordinate.parse, targets)
        if ok and getmetatable(parsed) == Coordinate then
            targets = {parsed}
        else
            for i, t in ipairs(targets) do
                if getmetatable(t) ~= Coordinate then
                    targets[i] = Coordinate.parse(t)
                end
            end
        end
    else
        error("dijkstra: invalid targets argument")
    end
    logger:debug("Starting Dijkstra algorithm from " .. tostring(source) .. " to multiple targets")
    local distance = {}
    local previous = {}
    local queue = BinaryHeap:new()

    -- Keys into `distance` and `previous` use integer hashes instead of
    -- `tostring(coord)` to avoid allocating thousands of short strings
    -- per call. ~10x reduction in GC pressure.
    distance[source:hash()] = 0
    queue:insert(source, 0)

    local targetReached = nil
    while not queue:isEmpty() do
        local current = queue:pop()
        for _, target in ipairs(targets) do
            if current:isEqual(target) then
                targetReached = target
                break
            end
        end
        if targetReached then
            break
        end
        for _, data in pairs(self:getNeighbours(current)) do
            local cHash = current:hash()
            local nHash = data.position:hash()
            local alt = distance[cHash] + self:getCost(data.type)
            if alt < (distance[nHash] or math.huge) then
                distance[nHash] = alt
                previous[nHash] = current
                queue:decreaseKey(data.position, alt + self:heuristic(data.position, targets))
            end
        end
    end

    if not targetReached then
        logger:warn("Dijkstra: no target reachable from " .. tostring(source))
        return {}, nil, nil
    end

    local path = {}
    local u = targetReached
    local cost = distance[u:hash()]
    if previous[u:hash()] or source:isEqual(u) then
        while u do
            table.insert(path, 1, u)
            u = previous[u:hash()]
        end
    end
    logger:debug("Finished Dijkstra algorithm from " .. tostring(source) .. " to multiple targets")
    logger:debug("Path length: " .. #path)
    for i, v in pairs(path) do
        logger:debug("Path[" .. i .. "]: " .. tostring(v))
    end
    logger:debug("Cost: " .. tostring(cost))

    if #path < 2 then
        return {}, targetReached, cost
    end
    return Distance.fromPath(path), targetReached, cost
end

function Environment:getCost(_blockType)
    if not _blockType then
        _blockType = blockType.UNKNOWN
    end
    if _blockType == blockType.FUEL or _blockType == blockType.AIR then
        return 1
    elseif _blockType == blockType.WASTE or _blockType == blockType.OTHER then
        return 10
    elseif _blockType == blockType.PATH then
        return 5
    else
        return 1000
    end
end

-- Add a heuristic function to estimate the cost from the current node to the target
function Environment:heuristic(current, targets)
    local minDistance = math.huge
    for _, target in ipairs(targets) do
        local dx = math.abs(current.x - target.x)
        local dy = math.abs(current.y - target.y)
        local dz = math.abs(current.z - target.z)
        local distance = dx + dy + dz -- Manhattan distance
        if distance < minDistance then
            minDistance = distance
        end
    end
    return minDistance
end

-- ---------------------------------------------------------------------------
-- Cache management & serialization
-- ---------------------------------------------------------------------------

-- Prune `checkedBlocks` entries whose Manhattan distance from `anchor`
-- exceeds `maxDistance`. Cheap LRU-ish substitute: if we've moved far
-- enough that we won't realistically revisit an area, forget it.
function Environment:prune(anchor, maxDistance)
    if getmetatable(anchor) ~= Coordinate then
        anchor = Coordinate.parse(anchor)
    end
    maxDistance = maxDistance or 100
    local removed = 0
    for y, ys in pairs(self.checkedBlocks) do
        local dy = math.abs(y - anchor.y)
        for x, xs in pairs(ys) do
            local dx = math.abs(x - anchor.x)
            for z, _ in pairs(xs) do
                if dx + dy + math.abs(z - anchor.z) > maxDistance then
                    xs[z] = nil
                    removed = removed + 1
                end
            end
            if next(xs) == nil then ys[x] = nil end
        end
        if next(ys) == nil then self.checkedBlocks[y] = nil end
    end
    if removed > 0 then
        logger:debug("Prune: dropped " .. removed .. " checkedBlocks entries beyond " .. maxDistance .. " from " .. tostring(anchor))
    end
    return removed
end

-- Serialize state to a plain Lua table suitable for textutils.serialize.
-- Block-type objects are reduced to their name strings.
function Environment:toState()
    local checked = {}
    for y, ys in pairs(self.checkedBlocks) do
        checked[y] = {}
        for x, xs in pairs(ys) do
            checked[y][x] = {}
            for z, bt in pairs(xs) do
                checked[y][x][z] = bt.name
            end
        end
    end
    local fuels = {}
    for y, ys in pairs(self.fuelLocations) do
        fuels[y] = {}
        for x, xs in pairs(ys) do
            fuels[y][x] = {}
            for z, _ in pairs(xs) do
                fuels[y][x][z] = true
            end
        end
    end
    return {
        checkedBlocks  = checked,
        fuelLocations  = fuels,
        currentPattern = Environment.currentPattern,
    }
end

-- Restore state previously written by :toState().
function Environment:loadState(state)
    if type(state) ~= "table" then return false end
    self.checkedBlocks = {}
    if type(state.checkedBlocks) == "table" then
        for y, ys in pairs(state.checkedBlocks) do
            self.checkedBlocks[y] = {}
            for x, xs in pairs(ys) do
                self.checkedBlocks[y][x] = {}
                for z, name in pairs(xs) do
                    -- Resolve block-type name back to the canonical table.
                    for _, bt in pairs(blockType) do
                        if bt.name == name then
                            self.checkedBlocks[y][x][z] = bt
                            break
                        end
                    end
                end
            end
        end
    end
    self.fuelLocations = {}
    if type(state.fuelLocations) == "table" then
        for y, ys in pairs(state.fuelLocations) do
            self.fuelLocations[y] = {}
            for x, xs in pairs(ys) do
                self.fuelLocations[y][x] = {}
                for z, _ in pairs(xs) do
                    self.fuelLocations[y][x][z] = blockType.FUEL
                end
            end
        end
    end
    if state.currentPattern and Environment.patterns[state.currentPattern] then
        Environment.currentPattern = state.currentPattern
    end
    return true
end

