---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by levi.
--- DateTime: 2/23/2024 3:21 PM
---

require('Logger')

local logger = Logger:new(Logger.levels.DEBUG, "Timer")

function trackTime()
    local sTime = table.concat( tArgs, " " )
    local nSeconds = 0
    for i, period in sTime:gmatch( "(%d+)%s+(%a+)s?" ) do
        if period:lower() == "second" then
            nSeconds = nSeconds + i
        elseif period:lower() == "minute" then
            nSeconds = nSeconds + ( i * 60 )
        elseif period:lower() == "hour" then
            nSeconds = nSeconds + ( i * 3600 )
        end
    end
    print( "[trackTime]: Starting timer for "..nSeconds.." seconds!" )
    local id = os.startTimer( nSeconds )
    while ok do
        local _, tid = os.pullEvent( "timer" )
        if id == tid then
            print( "[trackTime]: End of session reached!  Returning to base!" )
            ok = false
        end
    end
end